name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    strategy:
      matrix:
        go_version: [1.19.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - name: Build cross-platform
        run: ./build-all.sh
      - name: Run JReleaser
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ github.ref_name }}
